### ISSUE TITLE
Support GCE_METADATA_HOST env var

### ISSUE THREAD

**Issue by danielnorberg** [google/google-auth-library-java#105]
The `DefaultCredentialProvider` in `google-api-java-client` allows for specifying the GCE metadata server address using the `GCE_METADATA_HOST` environment variable.

https://github.com/google/google-api-java-client/blob/dev/google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/OAuth2Utils.java#L110

The golang google cloud library seems to offer the same capability.

https://godoc.org/cloud.google.com/go/compute/metadata#Get

It would be useful if `google-auth-library-java` supported this as well.

The commit implementing this in `google-api-java-client`: https://github.com/google/google-api-java-client/commit/7bb680f342a750b70bf5821fc43429a443c9563e

**Comment by chingor13** [comment]
This feature was added in #110 and available since 0.7.1. Closing this out, but feel free to re-open if this is not the case.
