### ISSUE TITLE
FR: Expose Project ID from ServiceAccountCredentials

### ISSUE THREAD

**Issue by hiranya911** [google/google-auth-library-java#117]
Currently the `com.google.auth.oauth2.ServiceAccountCredentials` class does not handle the `project_id` field available in Google service account JSON files. It would be useful if the credential can read this field, and expose it via a new `getProjectId()` method.

Usecase: We want to use this library within some Firebase SDKs, and we (in some situations) need to know the project ID along with the credential.

**Comment by chingor13** [comment]
Fixed in #118 and available since 0.8.0
