### ISSUE TITLE
Possible Integer Overflow When Parsing expires_in Values

### ISSUE THREAD

**Issue by hiranya911** [google/google-auth-library-java#120]
While running some tests using the `MockTokenServerTransport` of the Google API client, I noticed that sometimes `GoogleCredentials.getExpirationTime()` incorrectly returns timestamps that are several days old. This is what's going on:

1. `MockTokenServerTransport` has a bug where it reports the `expires_in` field in milliseconds (3600000), where it should be seconds. I reported this in their Github repo (https://github.com/google/google-api-java-client/issues/1061).
2. The code in `ServiceAccountCredentials` class will encounter an integer overflow, when the backend server reports a large `expires_in` value:

https://github.com/google/google-auth-library-java/blob/master/oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java#L375

```
    long expiresAtMilliseconds = clock.currentTimeMillis() + expiresInSeconds * 1000;
```

If `expiresInSeconds` is large (say 3600000), this code will overflow, and the resulting timestamp will be in the past.

**Comment by chingor13** [comment]
Fixed in #121 and available since 0.8.0
