### ISSUE TITLE
Outdated API Docs

### ISSUE THREAD

**Issue by hiranya911** [google/google-auth-library-java#133]
The API docs URL given in `index.md` is outdated: http://google.github.io/google-auth-library-java/releases/0.7.1/apidocs/

It doesn't look like the API docs of the last release (v0.8.0) are published anywhere. Please publish the latest API docs, and provide a version-neural permanent link like http://google.github.io/google-auth-library-java/releases/latest/apidocs/ so downstream projects can easily link to API docs of this library.

**Comment by chingor13** [comment]
The current link on the main `README.md` links to the current latest version.

The versionless URL for docs will be tracked in #113
