### ISSUE TITLE
auto-refreshing isn't work

### ISSUE THREAD

**Issue by headiron** [google/google-auth-library-java#139]
Hello all.

I routed here from google-doublecliek-ad-exchange-buyer-api group for OAuth auto-refresh issue. https://groups.google.com/forum/#!topic/google-doubleclick-ad-exchange-buyer-api/ptf3-LO-2Jc

I saw "GoogleCredential takes care of automatically "refreshing" the token" state from below page.
https://developers.google.com/api-client-library/java/google-api-java-client/oauth2

I wrote below but it doesn't refresh token automatically.

String token = ...;
TokenResponse tokenResponse = JacksonFactory.getDefaultInstance().fromString<TokenResponse>(token, TokenResponse.getClass());
tokenResponse.setRefreshToken("CCCCC");

Credential credential = new GoogleCredential.Builder().setJsonFactory(JacksonFactory.getDefaultInstance())
  .setTransport(GoogleNetHttpTransport.newTrustedTransport())
  .setClientSecrets("XXXX", "XXXX")
  .build().setFromTokenResponse(tokenResponse);
AdExchangeBuyerII buyer = new AdExchangeBuyerII.Builder(new NetHttpTransport(), JacksonFactory.getDefaultInstance(), credential).setApplicationName("").build();

Originally, I set refreshToken at GoogleCredential, but I change it to set it on TokenResponse after Mark's suggestion. But both of them isn't work.

I also add CredentialRefreshListener() to check whether refresh request is sent, but I can't see anyting.

Could you let me know whether my code need to be updated or it is a bug on auth library?

**Comment by JustinBeckwith** [comment]
Closing this as a dup of #147.  Thanks!
