### ISSUE TITLE
HttpCredentialsAdapter should refresh credentials if access token invalid

### ISSUE THREAD

**Issue by anthmgoogle** [google/google-auth-library-java#14]
An access token can become invalid separately from its expiration time due a clock mismatch or other scenarios. If a request fails because the access token is invalid, the adapter should call refresh() to discard the token and retry the request a single time. See google-api-java-client for a reference implementation.

**Comment by garrettjonesgoogle** [comment]
@anthmgoogle : bug or enhancement?

**Comment by chingor13** [comment]
Duplicate of #22. Closing this one in favor of that one as it has more links.
