### ISSUE TITLE
FR: Need a good way to inject secrets besides `gcloud` & `GOOGLE_APPLICATION_CREDENTIALS`

### ISSUE THREAD

**Issue by lesv** [google/google-auth-library-java#146]
PR's #94 & #144 both want to find a way to improve ADC for non-google cloud providers.

The [ADC](https://developers.google.com/identity/protocols/application-default-credentials) algorithm is defined to:

1. Look at environment variable GOOGLE_APPLICATION_CREDENTIALS
2. Look for gcloud auth application-default login
3. Get a service account from the GCP Metadata server (GAE & GCP are a bit different, but it's the same idea)

We should see if there is a way to safely and securely inject a secret like a service account JSON into a container running on another cloud platform. (item 3 above). 

@jonparrott said: environment variables [should not be used to hold secrets](https://diogomonica.com/2017/03/27/why-you-shouldnt-use-env-variables-for-secret-data/).

This is a very important item for us. We are trying get to the point where docker containers can run anywhere, on GCP, on a competing cloud provider, in their own datacenter, or locally in their laptop with just a change in the configuration.

**Comment by JustinBeckwith** [comment]
I'm not sure what more is available for us here.  @theacodes what other types of auth does python provide?

**Comment by theacodes** [comment]
Environment variables pointing to a *file* that holds the secret (instead of putting the secret *in* the environment variable) is the best practice. Let's close this.
