### ISSUE TITLE
Make ComputeEngineCredentials support createScoped

### ISSUE THREAD

**Issue by hzyi-google** [google/google-auth-library-java#148]
The implementation of `ComputeEngineCredentials` does not support scope, which makes `ComputeEngineCredential.createScoped` not attach scope as expected. This is causing working with Drive scopes on GAE java8 and GCE receiving errors (e.g. this [BigQuery auth issue](https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2552)) . Consider add support for scope in `ComputeEngineCredentials`.

**Comment by JustinBeckwith** [comment]
AFAIK, this is not actually possible. The scopes available to the GCE service accounts are determined at instance create time, and need to be queried from the GCE Metadata Server.  

Adding @theacodes to confirm my theory.

**Comment by theacodes** [comment]
Scopes for GCE credentials are fixed and can't be changed, only read. Python expresses this using a separate "ReadOnlyScoped" interface.

**Comment by alamothe** [comment]
Are there any workarounds?
