### ISSUE TITLE
Make google-auth-library-java compatible with Guava in [19.0, 24.0]

### ISSUE THREAD

**Issue by garrettjonesgoogle** [google/google-auth-library-java#153]
Remove references to anything that is not in all versions of that version range.

This might already be true, but it needs to be verified.

cc @lesv

**Comment by chingor13** [comment]
All `com.google.common` references:
- [ ] annotations.VisibleForTesting
- [ ] base.MoreObjects
- [ ] base.Preconditions
- [ ] base.Splitter
- [ ] base.Throwables
- [ ] base.Ticker
- [ ] cache.CacheBuilder
- [ ] cache.CacheLoader
- [ ] cache.LoadingCache
- [ ] collect.ImmutableList 
- [ ] collect.ImmutableMap 
- [ ] collect.ImmutableSet
- [ ] collect.Iterables
- [ ] io.ByteStream
- [ ] util.concurrent.UncheckedExecutionException

**Comment by chingor13** [comment]
All of the guava classes used are compatible
