### ISSUE TITLE
Is the JWT-permitted check in GoogleCredentialsProvider correct?

### ISSUE THREAD

**Issue by JustinBeckwith** [google/google-auth-library-java#161]
_From @chrisdunelm on June 20, 2018 17:42_

The JWT-permitted check in [GoogleCredentialsProvider.getCredentials()](https://github.com/googleapis/gax-java/blob/master/gax/src/main/java/com/google/api/gax/core/GoogleCredentialsProvider.java#L62) (line 62) appears incorrec to me.

It currently permits JWT use if *any* of the applied scopes are present in the "JWT-enabled" scopes.
However, shouldn't it only permit JWT use if *all* of the applied scopes are present in the "JWT-enabled" scopes?

Or have I misunderstood how this works?!? (very possible...)

_Copied from original issue: googleapis/gax-java#551_

**Comment by JustinBeckwith** [comment]
_From @chrisdunelm on June 20, 2018 17:43_

/cc @pongad

**Comment by chrisdunelm** [comment]
This issue can be closed. This was due to a misunderstanding on my part.
