### ISSUE TITLE
Change all types taking Collection<scopes> to do immutable copies

### ISSUE THREAD

**Issue by anthmgoogle** [google/google-auth-library-java#17]
Types like ServiceAccountCredentials handle lists of scopes. The types are effectively immutable, so for safety, all types taking collections of scopes should use ImmutableList.copy(scopes).

**Comment by ejona86** [comment]
ServiceAccountCredentials was the only place I saw that would need to be changed.

**Comment by chingor13** [comment]
`ServiceAccountCredentials` was fixed in #69 and have been available since 0.5.0.
