### ISSUE TITLE
GoogleCredentials getApplicationDefault broken on appengine standard environment for java 8

### ISSUE THREAD

**Issue by pievis** [google/google-auth-library-java#172]
Seems that all versions past 0.7.x of this library are broken when calling _GoogleCredentials.getApplicationDefault()_ on appengine standard environment with java 8

having a look in the code of the last version I notice that in the method getDefaultCredentialsUnsynchronized the following call is made

```
// Then try GAE 7 standard environment
    if (credentials == null && isOnGAEStandard7() && !skipAppEngineCredentialsCheck()) {
      credentials = tryGetAppEngineCredential();
    }

    // Then try Cloud Shell.  This must be done BEFORE checking
    // Compute Engine, as Cloud Shell runs on GCE VMs.
    if (credentials == null) {
      credentials = tryGetCloudShellCredentials();
    }

    // Then try Compute Engine and GAE 8 standard environment
    if (credentials == null) {
      credentials = tryGetComputeCredentials(transportFactory);
    }
```

making the application search for compute engine default credential, that then crashes with the following error:

> The Application Default Credentials are not available. They are available if running in Google Compute Engine.

or

> com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine: Failed to detect whether we are running on Google Compute Engine

I fixed it by reverting back (after MANY try and error) to the version 0.7.0 that works like a charm, getting the right service account credentials: 

```
    // Then try App Engine
    if (credentials == null && !skipAppEngineCredentialsCheck()) {
      credentials = tryGetAppEngineCredential();
    }

    // Then try Cloud Shell.  This must be done BEFORE checking
    // Compute Engine, as Cloud Shell runs on GCE VMs.
    if (credentials == null) {
      credentials = tryGetCloudShellCredentials();
    }

    // Then try Compute Engine
    if (credentials == null) {
      credentials = tryGetComputeCredentials(transportFactory);
    }
```

Is it a huge bug ? or the java 8 **standard** gae should actually search for compute engine default credentials ?

**Comment by chingor13** [comment]
Java 8 on App Engine Standard should use the Compute Engine credentials. The AppEngineCredentials are only for the legacy Java 7 runtime which utilizes the AppEngine SDK tools and uses legacy GAE Standard auth endpoints which are not available to the Java 8 runtime.

**Comment by pievis** [comment]
Sorry to bother, I need more insight on this.
When you create a new java 8 app engine standard project, and you deploy your first version, automatically an App Engine service account is created, this is the "default" service account.

you are telling me I should spawn a compute engine machine in order to create the compute engine default service account ? Will the code running on app engine machine actually retrieve that ?

**Comment by chingor13** [comment]
@pievis When you ask for the default credentials from `GoogleCredentials.getApplicationDefault()` you are getting back a `GoogleCredentials` object. This class represents the **strategy** used for fetching credentials on that system. 

For GAE Standard Java 8, you will get back a `ComputeEngineCredentials` instance - which means it tries to use the metadata server to authenticate. You don't need to spawn any compute engine machines - if this strategy is used, then it will use the automatically created "App Engine default service account" (it usually looks like `PROJECT_ID@appspot.gservicceaccount.com` and you can find it under the "IAM & admin > IAM" section in the Google Cloud Console.

**Comment by pievis** [comment]
@chingor13 thank you for the explanation. 

However what has happened to me in three different projects is that I can't get the default credentials by using that method, because it fails with the error messages shown above.

> com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine: Failed to detect whether we are running on Google Compute Engine

or

> The Application Default Credentials are not available. They are available if running in Google Compute Engine.

Instead, using the previous version (0.7.x) I correctly get the credentials. 
These projects in particular are all project that migrated from java7 to java8, should this affect the behaviour of getApplicationDefault() ?

These are the packages I've included in my last project, could it be something I'm missing ?  

```
<dependency>
            <groupId>com.google.appengine</groupId>
            <artifactId>appengine-remote-api</artifactId>
            <version>${gae.version}</version>
        </dependency>

        <dependency>
            <groupId>com.google.appengine</groupId>
            <artifactId>appengine-api-1.0-sdk</artifactId>
            <version>${gae.version}</version>
        </dependency>

<dependency>
            <groupId>com.google.auth</groupId>
            <artifactId>google-auth-library-oauth2-http</artifactId>
            <version>${google.auth.lib.version}</version>
        </dependency>

        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-bigquery</artifactId>
            <version>1.37.1</version>
            <exclusions>
                <exclusion>
                    <artifactId>guava-jdk5</artifactId>
                    <groupId>com.google.guava</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>guava</artifactId>
                    <groupId>com.google.guava</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>google-api-client</artifactId>
                    <groupId>com.google.api-client</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>google-auth-library-oauth2-http</artifactId>
                    <groupId>com.google.auth</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.google.oauth-client</groupId>
            <artifactId>google-oauth-client-appengine</artifactId>
            <version>${google-api-client.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.api-client</groupId>
            <artifactId>google-api-client-appengine</artifactId>
            <version>${google-api-client.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>guava-jdk5</artifactId>
                    <groupId>com.google.guava</groupId>
                </exclusion>
            </exclusions>
        </dependency>


        <dependency>
            <groupId>com.google.appengine.tools</groupId>
            <artifactId>appengine-gcs-client</artifactId>
            <version>${gcs-client.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava-jdk5</artifactId>
                </exclusion>
                <exclusion>
                    <artifactId>guava</artifactId>
                    <groupId>com.google.guava</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>google-api-client</artifactId>
                    <groupId>com.google.api-client</groupId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by zhihuawensc** [comment]
@pievis @chingor13 
I met similar problem and finally figured it out, it was because we have 
    <url-stream-handler>urlfetch</url-stream-handler>
in our appengine-web.xml, this was causing GoogleCredentials.getApplicationDefault() to use url fetch to get the gce service account, which will fail because of this.

Remove this line
    <url-stream-handler>urlfetch</url-stream-handler>
solved the problem

**Comment by zhihuawensc** [comment]
I mean removing 
```
    <url-stream-handler>urlfetch</url-stream-handler>
```
