### ISSUE TITLE
Add Google App Engine Service Account Support

### ISSUE THREAD

**Issue by anthmgoogle** [google/google-auth-library-java#2]
Add support for the GAE built-in service account, aka. App Identity. Also, add support to Application Default Credentials for detecting this environment and automatically using this identity.

**Comment by ajkannan** [comment]
From the public documentation, it looks like the Google Application Default Credentials can detect the App Engine service account.  Does that mean that this issue is now fixed?  cc/ @aozarov

**Comment by aozarov** [comment]
And if it was fixed how does it behave in AE dev appserver?

**Comment by anthmgoogle** [comment]
This was implemented in this library in February 2015. In the Dev App Server it picks up the local application default credentials for use as a proxy for the app identity.
