### ISSUE TITLE
HttpCredentialsAdapter should enable refresh and retry for expired or invalid access token

### ISSUE THREAD

**Issue by anthmgoogle** [google/google-auth-library-java#22]
The current HttpCredentialsAdapter will refresh the token if it detects that it has expired on the client side. However, the token can be invalided or expire earlier than this due to clock differences. The adaptere should also detect this case, refresh the token and retry the request.

As a reference, the equivalent credential class in the V1 library does this:
https://github.com/google/google-oauth-java-client/blob/dev/google-oauth-client/src/main/java/com/google/api/client/auth/oauth2/Credential.java

It will require the HttpCredentialsAdapter to implement the HttpUnsuccessfulResponseHandler interface.

**Comment by garrettjonesgoogle** [comment]
@anthmgoogle : Bug or enhancement?

**Comment by chingor13** [comment]
This was implemented in #24
