### ISSUE TITLE
Errors when using Application Default Credentials from within App Engine

### ISSUE THREAD

**Issue by ajkannan** [google/google-auth-library-java#45]
When using Application Default Credentials from App Engine, both on the local development server (after logging in via `gcloud auth login`) and in production, I get the following error message:
java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

Based on that website, it seems like the behavior should be that the SDK credentials are used in the local development server and the App Engine credentials should be provided without setting the GOOGLE_APPLICATION_CREDENTIALS environment variable.

**Comment by ajkannan** [comment]
Turns out this was a mistake on my part.  In our maven project, we took a dependency on the `oauth2_http` and `credentials` modules, but not the `appengine` module.

**Comment by anthmgoogle** [comment]
OK. It may be worth creating a new issue along the lines of improving the error message in this case.

**Comment by aozarov** [comment]
@anthmgoogle is there a way to avoid pulling appengine-api-1.0-sdk (17Mb jar) when not necessary.

Few options: 
- Use "provided" or a like as a maven dependency
- Use reflection to invoke methods on `AppIdentityService`

`gcloud-java` used to do the latter.

**Comment by Raviraj20** [comment]
Getting an similar error when using an .Net 
Can someone help how to solve this error 

Message":"An error has occurred.","ExceptionMessage":"The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.","ExceptionType":"System.InvalidOperationException","StackTrace":" at Google.Api.Gax.TaskExtensions.WaitWithUnwrappedExceptions(Task task)\r\n at Google.Api.Gax.Grpc.ChannelPool.GetChannel(ServiceEndpoint

**Comment by garrettjonesgoogle** [comment]
@Raviraj20 you code looks like C# - did you want https://github.com/googleapis/gax-dotnet ?

**Comment by Raviraj20** [comment]
@garrettjonesgoogle 
ya but that to not working showing an similar error 
"ExceptionMessage":"The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable 

we cant put the credential file in  root folder 
*.json

**Comment by Raviraj20** [comment]
@garrettjonesgoogle
thanks for replying 
this  https://github.com/googleapis/gax-dotnet  this project is not geting open 
in vs 2015 

geting this error
![image](https://cloud.githubusercontent.com/assets/25105115/25648489/17555d38-2fea-11e7-9fce-a5b25ba01536.png)

**Comment by Raviraj20** [comment]
@garrettjonesgoogle
thanks for replying
this https://github.com/googleapis/gax-dotnet this project is not geting open
its showing a error 
this https://github.com/googleapis/gax-dotnet this project is not geting open
![image](https://cloud.githubusercontent.com/assets/25105115/25648632/a06878ac-2feb-11e7-9644-064bb665ad7f.png)

**Comment by garrettjonesgoogle** [comment]
@Raviraj20 , what I meant was that you should file an issue using https://github.com/googleapis/gax-dotnet/issues/new to have the owners of gax-dotnet look at it for you. I can't help you here because this repository is for Java issues.

**Comment by Raviraj20** [comment]
@garrettjonesgoogle 
ok thanks

**Comment by randolfo75** [comment]
I solved the same problem here running: gcloud auth **application-default** login. I hope helps somebody.

**Comment by chingor13** [comment]
The original issue appears to be resolved and it's unclear why it was reopened. Closing this out, but feel free to re-open if this is not the case.
