### ISSUE TITLE
Getters for UserCredentials member variables

### ISSUE THREAD

**Issue by ajkannan** [google/google-auth-library-java#52]
Is there a reason that [UserCredentials](https://github.com/google/google-auth-library-java/blob/master/oauth2_http/java/com/google/auth/oauth2/UserCredentials.java)' member variables don't have public getters? It would be useful to have getters like in [ServiceAccountCredentials](https://github.com/google/google-auth-library-java/blob/master/oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java#L260).

**Comment by anthmgoogle** [comment]
No reason not to add them. These should be added.

**Comment by ajkannan** [comment]
Thanks for adding this!  Is there a chance we can get an artifact pushed to maven with this change?

**Comment by pongad** [comment]
This is already included in v0.4.0. So I'm closing this
