### ISSUE TITLE
Provide a method to write User Credentials to file

### ISSUE THREAD

**Issue by ajkannan** [google/google-auth-library-java#54]
It would be helpful to give users the ability to generate a User Credentials JSON file.  While this is a feature of [Python's auth library](https://github.com/google/oauth2client/blob/master/oauth2client/client.py#L246), the only way users can get a User Credentials JSON file now is to login using the Google Cloud SDK and then go hunting for it in the configurations directory.

**Comment by tswast** [comment]
There's already a [TokenStore](https://github.com/google/google-auth-library-java/blob/master/oauth2_http/java/com/google/auth/oauth2/TokenStore.java) interface which seems to be intended for this purpose, but no concrete implementation is provided.

**Comment by YuryBandarchuk16** [comment]
Hello! Can I work on this enhancement?

Thanks!

**Comment by tswast** [comment]
Contributions welcome! Per [the contributions document](https://github.com/google/google-auth-library-java/blob/master/CONTRIBUTING.md), before we can accept a pull request from you, we'll need a signed CLA.

For the first implementation, we'd probably want an in-memory version. Basically just enough to have a working TokenStore implementation. That way an application could use user authentication but would have to re-authenticate every time.

Second, I'd want something that can save refresh tokens to a JSON file in a configuration directory. It's a different language, but something similar to what is done in the Pandas-GBQ library: https://github.com/pydata/pandas-gbq/blob/dbfb4e92d4b26fe5cff6c22e9ae420b324b8ac5a/pandas_gbq/gbq.py#L304

**Comment by YuryBandarchuk16** [comment]
@tswast There is my PR for this issue -  #129 

Instead of only having the refresh tokens, I store a few other things. The implementation works in such way, so that if you call the method that saves userCredentials, it will overwrite everything what existed before. Let me know if you would like any changes.

**Comment by YuryBandarchuk16** [comment]
Opened #129 for this issue.

**Comment by chingor13** [comment]
This appears to have been fixed in #129 by with `OAuth2Utils.writeInputStreamToFile()` and `UserCredentials.save()`.

Closing this out, but feel free to re-open if this is not the case.
