### ISSUE TITLE
FR: Need a more detailed README

### ISSUE THREAD

**Issue by lesv** [google/google-auth-library-java#57]
Readme should be a bit more detailed, including:
- How to include this in Maven / Gradle
- Current version
- How to use or a link to documentation
- Link to license and Contributing

See https://github.com/GoogleCloudPlatform/Template for suggested outline.

**Comment by anthmgoogle** [comment]
Agreed.

**Comment by mziccard** [comment]
Before adopting this library in `google-cloud-java` we should fix this. Also, do we have the javadoc available somewhere? If not, can we use gh-pages for it (similar to what [guava](https://google.github.io/guava/releases/19.0/api/docs/) does)?

@lesv Is this library referenced from official docs? I see that [in this page](https://developers.google.com/identity/protocols/application-default-credentials#callingjava) the REST Apiari's credentials are introduced instead.

/cc @garrettjonesgoogle

**Comment by lesv** [comment]
I was just looking for this in official docs, can't seem to find.

**Comment by garrettjonesgoogle** [comment]
I'm fine with using gh-pages.

**Comment by lesv** [comment]
I'm happy w/ just gh-pages & the readme.
