### ISSUE TITLE
Check CLOUDSDK_CONFIG for default credentials location

### ISSUE THREAD

**Issue by ajkannan** [google/google-auth-library-java#58]
In [DefaultCredentialsProvider.getWellKnownCredentialsFile()](https://github.com/google/google-auth-library-java/blob/master/oauth2_http/java/com/google/auth/oauth2/DefaultCredentialsProvider.java#L155), the environment variable CLOUDSDK_CONFIG isn't checked.  Instead, it assumes that the `.config` directory is in home.  If the CLOUDSDK_CONFIG environment variable is set, that should be used instead of home.  This would be consistent with the issue reported in the python equivalent of this library (see this [issue](https://github.com/google/oauth2client/issues/151#issuecomment-87772942)).

As a result of not checking CLOUDSDK_CONFIG, users can see the [issues like this](https://github.com/GoogleCloudPlatform/gcloud-java/issues/680) if they install Cloud SDK in a non-default location.

**Comment by aozarov** [comment]
ping. /cc @anthmgoogle

**Comment by anthmgoogle** [comment]
@lesv @ejona86. Agree this is a bug that should be fixed.

**Comment by lesv** [comment]
I'll try to go through all of these issues next week.

**Comment by mziccard** [comment]
I believe this was fixed in #63
