### ISSUE TITLE
FR: please give us a way to find Project ID

### ISSUE THREAD

**Issue by lesv** [google/google-auth-library-java#87]
The other languages are trying to pickup current / default ProjectID - since SQL v2, bigtable, and other services require .

We possibly may need to get the default zone & region from gcloud config.

**Comment by garrettjonesgoogle** [comment]
Project id is independent from auth. We have this functionality now in google-cloud-java at https://github.com/GoogleCloudPlatform/google-cloud-java/blob/5cbbbae1ac80aecfa742972097c705eb8871930c/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java#L286 . Resolving this issue.
